"""
LLM client for base Nemotron-Nano-9B inference via NIM container.
Exposes an OpenAI-compatible chat/completions interface.
"""

import logging
from typing import Any

from config import settings

logger = logging.getLogger(__name__)

_client: Any = None


def get_client():
    global _client
    if _client is None:
        try:
            _openai = __import__("openai")
            _client = _openai.OpenAI(
                base_url=f"{settings.nim_url}/v1",
                api_key="not-needed",
            )
        except Exception as exc:
            logger.warning("OpenAI client unavailable: %s", exc)
            _client = "unavailable"
    return _client


def chat(
    messages: list[dict[str, str]],
    temperature: float = 0.7,
    max_tokens: int = 1024,
    model: str = "nvidia/nvidia-nemotron-nano-9b-v2-dgx-spark",
) -> str:
    """Synchronous chat completion via NIM."""
    try:
        client = get_client()
        if client == "unavailable":
            return _fallback_response(messages)
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=temperature,
            max_tokens=max_tokens,
        )
        return response.choices[0].message.content
    except Exception as e:
        logger.warning(f"NIM chat failed: {e}")
        return _fallback_response(messages)


def _fallback_response(messages: list[dict]) -> str:
    """Offline fallback when NIM is not available."""
    last_msg = messages[-1]["content"] if messages else ""
    return (
        f"[Offline mode - NIM container not available]\n\n"
        f"Your query: {last_msg[:200]}\n\n"
        f"This response would be generated by Nemotron-Nano-9B when the NIM "
        f"container is running. Start the container with:\n"
        f"  docker compose up nemotron-nim\n\n"
        f"The model will then provide domain-specific pricing analysis."
    )


PRICING_SYSTEM_PROMPT = """You are an expert pricing analyst AI assistant. 
You help pricing analysts, managers, and VPs understand pricing dynamics, 
interpret model outputs, and make data-driven pricing decisions.

Your expertise includes:
- Price elasticity interpretation
- Competitive pricing strategy
- SHAP/feature importance explanation in business terms
- Time series forecast interpretation
- Optimization trade-off analysis
- Anomaly detection and alerting
- Market trend analysis

Always ground your answers in the data and model outputs provided. 
Be precise with numbers and explain statistical concepts in business language."""


def pricing_chat(query: str, context: str = "", temperature: float = 0.5) -> str:
    """Pricing-domain chat with system prompt."""
    messages = [
        {"role": "system", "content": PRICING_SYSTEM_PROMPT},
    ]
    if context:
        messages.append({"role": "user", "content": f"Context:\n{context}\n\nQuestion: {query}"})
    else:
        messages.append({"role": "user", "content": query})
    return chat(messages, temperature=temperature)
