#!/usr/bin/env bash
set -euo pipefail

DATA_DIR="backend/data/raw"
PYTHON_BIN="backend/.venv/bin/python"

mkdir -p "$DATA_DIR"

if [ ! -x "$PYTHON_BIN" ]; then
  echo "Backend virtualenv not found at $PYTHON_BIN"
  echo "Create it first, then rerun this script."
  exit 1
fi

echo "=== Fuel Pricing Intelligence Lab - One-Time Data Ingestion ==="
echo ""

(
cd backend
.venv/bin/python - <<'PY'
from data import cache
from data.generator import build_all_datasets

existing = cache.load_all_from_db()
if existing:
    print("Database already seeded. Skipping re-download/rebuild.")
    for key, df in existing.items():
        print(f"  {key}: {len(df)} rows")
else:
    print("No persisted dataset found. Building and persisting now...")
    datasets = build_all_datasets(force=True)
    for key, df in datasets.items():
        print(f"  {key}: {len(df)} rows")
PY
)

echo ""
echo "=== Data ingestion complete ==="
echo "Files in $DATA_DIR:"
ls -lh "$DATA_DIR/" 2>/dev/null || echo "  (raw files are generated by loaders on demand)"
